version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer
    environment:
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_MAIL}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PATH: ${VIRTUAL_PATH}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    expose:
      - ${VIRTUAL_PORT}

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/home
    ports:
      - '9906:3306'

networks:
  default:
    external:
      name: aznable