version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '9906:3306'

networks:
  default:
    external:
      name: aznable